import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeToggle } from "@/components/theme-toggle";
import { ThemeProvider } from "@/providers/theme";

import { ViewportIndicator } from "@/components/viewport-indicator";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "code playground",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Suspense
						fallback={
							<div className="flex items-center justify-center h-screen">
								<div className="relative w-[44px] h-[44px] animate-cube-spin [transform-style:preserve-3d]">
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:translateZ(-22px)_rotateY(180deg)]" />
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:rotateY(-270deg)_translateX(50%)] [transform-origin:top_right]" />
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:rotateY(270deg)_translateX(-50%)] [transform-origin:center_left]" />
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:rotateX(90deg)_translateY(-50%)] [transform-origin:top_center]" />
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:rotateX(-90deg)_translateY(50%)] [transform-origin:bottom_center]" />
									<div className="absolute w-full h-full border-2 border-[#004dff] bg-[rgba(0,77,255,0.2)] [transform:translateZ(22px)]" />
								</div>
							</div>
						}
					>
						<TooltipProvider>{children}</TooltipProvider>
					</Suspense>
					<Toaster />
					<ThemeToggle />
					<ViewportIndicator />
				</ThemeProvider>
			</body>
		</html>
	);
}
