export const data = [
	{
		id: "Nike Mercurial Superfly 10 Academy",
		type: "FG",
		description: "High-Top Football Boot",
		colors: 2,
		price: 10319,
		sustainable: false,
	},
	{
		id: "Nike Tiempo Legend 10 Club",
		type: "FG",
		description: "High-Top Football Shoes",
		colors: 3,
		price: 17638,
		sustainable: true,
	},
	{
		id: "Nike United Phantom Luna 2 Elite",
		type: "TF",
		description: "High-Top Football Boot",
		colors: 2,
		price: 8035,
		sustainable: true,
	},
	{
		id: "Nike Phantom GX 2 Academy EasyOn Electric",
		type: "AG",
		description: "High-Top Football Shoes",
		colors: 1,
		price: 21888,
		sustainable: false,
	},
	{
		id: "Nike Tiempo Legend 10 Elite",
		type: "FG",
		description: "High-Top Football Boot",
		colors: 1,
		price: 18590,
		sustainable: true,
	},
	{
		id: "Nike Mercurial Vapor 16 Elite",
		type: "TF",
		description: "Low-Top Football Cleats",
		colors: 1,
		price: 7738,
		sustainable: false,
	},
	{
		id: "Nike Mercurial Superfly 10 Club",
		type: "IC",
		description: "Low-Top Football Cleats",
		colors: 1,
		price: 8839,
		sustainable: false,
	},
	{
		id: "Nike Phantom Luna 2 Elite Electric",
		type: "FG",
		description: "High-Top Football Boot",
		colors: 2,
		price: 14700,
		sustainable: false,
	},
	{
		id: "Nike Phantom GX 2 Academy 'Erling Haaland'",
		type: "FG",
		description: "Low-Top Football Cleats",
		colors: 5,
		price: 18382,
		sustainable: false,
	},
	{
		id: "Nike United Phantom GX 2 Elite",
		type: "AG",
		description: "Low-Top Football Cleats",
		colors: 2,
		price: 18508,
		sustainable: true,
	},
	{
		id: "Nike United Mercurial Superfly 10 Elite",
		type: "IC",
		description: "Low-Top Football Cleats",
		colors: 1,
		price: 19500,
		sustainable: true,
	},
	{
		id: "Nike United Mercurial Vapor 16 Elite",
		type: "IC",
		description: "High-Top Football Boot",
		colors: 5,
		price: 5313,
		sustainable: false,
	},
	{
		id: "Nike Mercurial Superfly 10 Elite By You",
		type: "AG",
		description: "High-Top Football Boot",
		colors: 2,
		price: 21481,
		sustainable: false,
	},
	{
		id: "Nike Mercurial Vapor 16 Academy By You",
		type: "TF",
		description: "High-Top Football Boot",
		colors: 2,
		price: 21511,
		sustainable: true,
	},
	{
		id: "Nike Mercurial Superfly 10 Academy By You",
		type: "AG",
		description: "High-Top Football Boot",
		colors: 1,
		price: 7140,
		sustainable: false,
	},
	{
		id: "Nike Tiempo Legend 10 Academy",
		type: "AG",
		description: "High-Top Football Boot",
		colors: 2,
		price: 8685,
		sustainable: false,
	},
	{
		id: "Nike Phantom Luna 2 Club",
		type: "AG",
		description: "High-Top Football Shoes",
		colors: 3,
		price: 18233,
		sustainable: true,
	},
	{
		id: "Nike Lunar Gato II",
		type: "TF",
		description: "High-Top Football Boot",
		colors: 3,
		price: 8035,
		sustainable: true,
	},
	{
		id: "Nike Mercurial Vapor 16 Academy 'Kylian Mbappé'",
		type: "FG",
		description: "High-Top Football Shoes",
		colors: 4,
		price: 8574,
		sustainable: false,
	},
	{
		id: "Nike Superfly 10 Academy Mercurial Dream Speed",
		type: "TF",
		description: "High-Top Football Boot",
		colors: 4,
		price: 18994,
		sustainable: false,
	},
	{
		id: "Nike Superfly 10 Elite Mercurial Dream Speed",
		type: "FG",
		description: "High-Top Football Shoes",
		colors: 5,
		price: 11339,
		sustainable: true,
	},
];